### ISSUE TITLE
getting invalid syntax when trying to run the config tool 

### ISSUE THREAD

**Issue by uyoyo117** [jfedor2/hid-remapper#1]
the message i get is:
 File "remapper-config.py", line 175
    f"{d['manufacturer_string']} {d['product_string']}",
                                                                               ^
SyntaxError: invalid syntax

i am running it on ubuntu python 3.7, it is also a problem in the config tool for the two balls trackball

**Comment by jfedor2** [comment]
That would be the error you'd get if you tried to run it with Python 2. Are you sure you're using Python 3?

**Comment by uyoyo117** [comment]
my bad, I used python instead of python 3
