### ISSUE TITLE
Switching to a layer exclusively 

### ISSUE THREAD

**Issue by Kn0rk** [jfedor2/hid-remapper#112]
So I have the following scenario I have my default layer (0) that includes home row mods. So if I tap the J key it just prints the J key. If i hold the J key it changes to a shift. While this is quite cool sometimes hold behaviour can be troublesome so i have a second layer(2) that can be toggled with the _insert_ key and all it does is remove the hold behaviour.

Finally i have a third layer that i want to use as a navigation layer. This layer should be accessible through the default layer as well as the layer2. With the setup below it works on the default layer. On layer_2 however it will activate layer_3 while layer_2  is still active. So it will print the j and the _return_ character.

Is there a way to prevent this? Can i switch to a layer rather than activating it?
![grafik](https://github.com/jfedor2/hid-remapper/assets/12850488/b09458c6-d075-4435-8e83-67fee34b66f0)

[sample_config.json](https://github.com/jfedor2/hid-remapper/files/14281292/sample_config.json)

**Comment by jfedor2** [comment]
It's not the most straightforward solution, but I think you can implement it like this.

The way it works is it uses Layer 1 as a helper layer and Layer 2 is activated by an expression that says "true if Layer 1 is active, but not Layer 3".
[activate_layer_exclusively.json](https://github.com/jfedor2/hid-remapper/files/14351461/activate_layer_exclusively.json)
![Screenshot from 2024-02-20 22-45-21](https://github.com/jfedor2/hid-remapper/assets/2271721/18e01259-4a0d-4b53-80a4-0bb27f47c7fa)
![Screenshot from 2024-02-20 22-35-25](https://github.com/jfedor2/hid-remapper/assets/2271721/4974ce48-a2d7-48e9-810c-aee409d6bca5)
![Screenshot from 2024-02-20 22-35-37](https://github.com/jfedor2/hid-remapper/assets/2271721/be7fdceb-c179-436b-bc84-1f5979141249)

**Comment by Kn0rk** [comment]
Thanks! I would not have been able to come up with that expression. I just tested it and it works.
