### ISSUE TITLE
Problem with arrow keys in macro

### ISSUE THREAD

**Issue by cptstan** [jfedor2/hid-remapper#124]
Arrow keys in macros just don't work as expected if they do actually fire.

For example this macro: A←B←C←

When testing in a text editor, I would expect the result to be: cba (with cursor to the left of the c) 
but i get: abc (with cursor to the left of the c)

**Comment by jfedor2** [comment]
Does your macro look like this:
![Screenshot from 2024-04-03 22-49-55](https://github.com/jfedor2/hid-remapper/assets/2271721/70097eae-ba86-4713-89b8-eb5b858500cf)
or like this:
![Screenshot from 2024-04-03 22-51-34](https://github.com/jfedor2/hid-remapper/assets/2271721/68fb34ef-874e-4a8a-897b-2507551e1b6f)
?

**Comment by cptstan** [comment]
yes it does

**Comment by jfedor2** [comment]
When the keys are in the same row, they're pressed at the same time.

Rows are executed sequentially.

Make it look like the first one.

**Comment by cptstan** [comment]
Ah, i understand.

Thank you
