### ISSUE TITLE
Error when using r2024-05-29 or  r2024-05-23

### ISSUE THREAD

**Issue by HandisableL** [jfedor2/hid-remapper#138]
When using this two version firmware,Web Configuration Tool show "TypeError: expr.matchAll.map is not a function or its return value is not iterable"
![2024-06-01 000904](https://github.com/jfedor2/hid-remapper/assets/81951753/015d963c-b6a0-41b3-a6f5-6a8842276e43)

I can load settings from device,but can't save to device(click "save to device",my usb keyborad  dongle just stop working,and nothing show in Configuration Tool-Monitor),unplug and plug remapper back,things work,but reverse to settings before save.
And sometime LED on the board just dont light.until press reset on board.
flash back r2024-04-19 can fix this problem.

**Comment by jfedor2** [comment]
What configuration do you have on the HID Remapper that you observer this issue with? Can you post a screenshot of the Expressions tab or an exported JSON file?

**Comment by jfedor2** [comment]
I will look into it, but can you try it in Chrome?
