### ISSUE TITLE
recommended use of multicore in the single Pico version

### ISSUE THREAD

**Issue by ams1** [jfedor2/hid-remapper#141]
Hi,

First just let me say this is one of the most useful repos for me, which I've just discovered (not sure how I've missed it so far).
@jfedor2 you're just awesome for creating/maintaining this, THANK YOU 🙏.

The question: In the SINGLE Pico version I want to do something with the 2nd core - I think that's NOT used now, right? Any plans to use it in the future?

Sorry for maybe asking an obvious question, but c/c++ is not my main weapon of choice - the inclusion of `pico_multicore` throws me off as I cannot find anything else starting with `multicore`.

Again, thank you so much.

P.S.: Have you considered enabling GitHub Sponsors?

**Comment by jfedor2** [comment]
`pico_multicore` is not used anymore, I just forgot to remove it.

I don't have plans for the second core at the moment.
