### ISSUE TITLE
Feature Request: Volume Up/Down Senativity

### ISSUE THREAD

**Issue by alvin-000** [jfedor2/hid-remapper#142]
Request for feature like scaling for mouse that would work for volume control. Instead of moving the default volume up/down interval, it would allow a multiplier (such as x2 or x5 speed). Any help would be much appreciated,I did try to just repeat the keys as a macro, but it did not work.

**Comment by jfedor2** [comment]
I just tried it with a macro and it seems to be working correctly.

Just remember to add "Nothing" between the "Volume up" entries.

<img width="715" alt="Screenshot 2024-06-09 at 14 26 42" src="https://github.com/jfedor2/hid-remapper/assets/2271721/a68f65e7-412f-4548-a072-d8c37a930f3f">

**Comment by alvin-000** [comment]
Thank you, that was it; I did not put in the Nothing in between and the computer interpreted it as just one long command.
