### ISSUE TITLE
Add Layer Cycling

### ISSUE THREAD

**Issue by IBNobody** [jfedor2/hid-remapper#16]
The current setup binds layer shifts to a button. That button can be sticky. This allows for a sniper-assist mode, which is good. However, it only allows for one set of scaling (tied to the layer you are on).

It would be nice if layers could be cycled rather than toggled. 

Press Middle Mouse Button -> Activate Layer 1 with 0.5 X/Y scaling
Press Middle Mouse Button Again -> Deactivate Layer 1, Activate Layer 2 with 0.25 X/Y scaling

**Comment by jfedor2** [comment]
If we solved #9, this could be done by configuring a different mapping for the "cycle" button on each layer (switching to the next layer), but we can probably also implement this separately.

**Comment by jfedor2** [comment]
With the latest release, this is now possible. You can define the mappings like so:

![Screenshot from 2023-01-20 00-07-06](https://user-images.githubusercontent.com/2271721/213582338-3bfb988e-a0fb-439f-af69-d2c461efaf3a.png)

(I also added an example that you can click on the config website that sets these.)
