### ISSUE TITLE
PS/2 to HID?

### ISSUE THREAD

**Issue by neuhaus** [jfedor2/hid-remapper#168]
I have an old IBM keyboard with PS/2 port and a separate USB interface for it that has some wrong mappings.
Instead of using this hid-remapper and the USB PS/2 interface together, what would it take for the hid-remapper to be able to talk PS/2 directly?

**Comment by jfedor2** [comment]
I've done some experiments with PS/2, but I don't have a "PS/2 HID Remapper" at this time. It would have to be something similar to what we have for serial mice.

**Comment by neuhaus** [comment]
(this isn't completed but i no longer require it)
