### ISSUE TITLE
Button6-8 does not work in Dual Version

### ISSUE THREAD

**Issue by shiiba-cba** [jfedor2/hid-remapper#17]
Buttons 6-8 work on Single Version, but not on Dual Version.
- DEFT
- HUGE
- Slimblade

The usage_map in quirks.cc is not working properly.

**Comment by jfedor2** [comment]
This should be fixed in c86148b. Please verify if you can.

**Comment by shiiba-cba** [comment]
Thanks. I have confirmed that the 6-8 buttons work on the Dual version.
