### ISSUE TITLE
Question regarding high speed instead of full speed usb for >1khz polling

### ISSUE THREAD

**Issue by shriramhr** [jfedor2/hid-remapper#22]
Hi JF, 

Is there a way to program the pico so that it selects usb high speed instead of full speed? If this is possible then maybe devices can be forced to poll at greater than 1 KHz.

**Comment by jfedor2** [comment]
The hardware doesn't support High Speed. The Pico-PIO-USB library doesn't either.

**Comment by shriramhr** [comment]
> The hardware doesn't support High Speed. The Pico-PIO-USB library doesn't either.

So technically if this code can be replicated for a different pi board which supports HS usb, it should work right?

**Comment by jfedor2** [comment]
In principle, yes. Some parts of the code are specific to the RP2040, in particular the overclocking stuff, but something similar could be done on another chip.
