### ISSUE TITLE
Scrolling Up and Scrolling down

### ISSUE THREAD

**Issue by AaronLea** [jfedor2/hid-remapper#31]
Has anyone found a way to differentiate VScroll so scrolling up can be remapped differently than scrolling down?

**Comment by jfedor2** [comment]
Depends on what you mean. If you want to map scroll up/down to two different keys, say, left arrow and right arrow, you can do it using scaling=1 and scaling=-1. But if you want to map scroll up to cursor X and scroll down to cursor Y or something like that then I'm afraid that's not currently possible.

**Comment by jfedor2** [comment]
Should be possible with expressions.
