### ISSUE TITLE
Idea for Pico W

### ISSUE THREAD

**Issue by hkfuertes** [jfedor2/hid-remapper#36]
I don´t know if this is the place to put this... but I got an idea for PICOW. Why don't expose a sensor over MQTT that will send the key pressed (either only the unmapped or all of them) so that the "stream" deck could also interface with HomeAssistant for light control?

It will require the tool to have wifi config section, and mqtt config section....

**Comment by urfdvw** [comment]
Having a keyboard shortcuts turning on the light is cool. However, I still feel this is a little off the scoop of this repo. Let's see what is the decision of the author.
