### ISSUE TITLE
support game controller / other HID devices

### ISSUE THREAD

**Issue by clore-hub** [jfedor2/hid-remapper#41]
i am looking for a possibility to remap USB game controller as HID keyboard. 
my used controller (xbox) was not recognized and I couldn't find any hints for gamepad compatibility in this repo.

I know, that the used tiny USB and PICO-PIO_USB libs are capable of this, but it seems not implemented (yet). my coding skills are just too bad to figure it out myself.

**Comment by jfedor2** [comment]
Some points.

1. Game controllers are kind of supported already - buttons only.
2. Full support, including joysticks, d-pads and triggers is planned.
3. The above applies to USB HID game controllers, so basically everything _except_ Xbox controllers, which, as far as I know, use a proprietary protocol for no good reason.

**Comment by clore-hub** [comment]
@jfedor2 : thx for the update! 
i already expected to be let down by the xbox propritary crap... but it is atm my only available controller. 
the remapper works as described with my basic Dell mouse and keyboard, but for my use case it has to be work as hardware  Gamepad --> Keyboard translator/remapper (work machine, no software remapper installable). 
I will get a basic USB Gamepad and wait for your planned input implementations!
