### ISSUE TITLE
Honor Scaling magnitude for mouse cursor to keystroke action

### ISSUE THREAD

**Issue by ipopov** [jfedor2/hid-remapper#55]
Fantastic project!

I have a small feature request that occurred to me as I enjoyed experimenting with it this weekend.

# Scaling for mouse movement to keystroke action 

I want to make the following mapping: in a certain layer, hold Alt, and convert Mouse Y movement into Tab/Shift-Tab. (This will let me quickly scrub across all my open windows.) This mapping works, but it seems like _any_ amount of mouse movement generates a keystroke: i.e. the magnitude of the "Scaling" field is ignored (thankfully, its sign is respected). So it absolutely blazes across all my windows at a rate faster than I can see.

It would be cool to _honor_ the magnitude of the Scaling field for these mappings. Then, I would have to move my cursor, say 10 "pixels" for another Tab keystroke to be generated.

I might take a look at implementing this myself - the code looks approachable. It would probably be something like how scaling works for scroll actions. However, filing this here upfront for opinions and suggestions. 😄

**Comment by jfedor2** [comment]
If you're willing to play around with expressions, take a look at this entry in the Examples tab: "mouse movement to arrow keys, but number of keypresses is proportional to distance". It pretty much does what you described. You might have to fine-tune the numbers for your use case.
