### ISSUE TITLE
"Unique" device names all seem to end with "O8".

### ISSUE THREAD

**Issue by jfedor2** [jfedor2/hid-remapper#72]

**Comment by jfedor2** [comment]
Wait, no, not all of them.

**Comment by dglaude** [comment]
I have 3 "Adafruit RP2040 Feather with USB Host" and they are all "VMO8" (I connected them one by one, not simultaneously).
Maybe now that I have that many, I have some interest in the unique name be unique.

**Comment by jfedor2** [comment]
It seems I used the first 20 bits of the serial number for the name and that turned out to be not that unique.

The latest release now uses the last 20 bits, which should be better.
