### ISSUE TITLE
Monitor tab doesn't recognize extra buttons

### ISSUE THREAD

**Issue by whiskthecat** [jfedor2/hid-remapper#75]
Hello, I am using Elecom Huge and the monitor tab doesn't respond when I click Fn1 Fn2 or Fn3.

**Comment by jfedor2** [comment]
Do the other buttons show up in the monitor tab?

Is it wired or wireless Huge?

**Comment by whiskthecat** [comment]
It's wireless huge. Yes the normal mouse buttons and the cursor show up in the monitor tab. I tried running wireshark USB capture to figure it out but I'm not making any sense out of it and there are tons of hex codes on the input selection page.

**Comment by jfedor2** [comment]
It seems you have a new variant of the Huge. We already have some special handling for product ID 0x010d, but yours is 0x011c.

I found some related patches in the Linux kernel, but it's not clear to me if the new variant has the same report descriptor (it's definitely broken in a similar way though).

Can you try to dump the report descriptor with Wireshark again? Just do the same thing you did previously, but unplug and re-plug the device while the capture is running.

(I know it might seem that this is what the Monitor tab was supposed to save us from, but sadly it doesn't, at least in its current version. If the report descriptor is broken then we still can't access the inputs. Something to consider in the future.)

**Comment by whiskthecat** [comment]
[hugeplug.zip](https://github.com/jfedor2/hid-remapper/files/11625303/hugeplug.zip)

**Comment by jfedor2** [comment]
Perfect, thanks.

The descriptor is indeed different, but still broken.

Please try this firmware build and let me know if it helps.

[elecom_huge_011c.zip](https://github.com/jfedor2/hid-remapper/files/11627534/elecom_huge_011c.zip)

**Comment by whiskthecat** [comment]
That worked, you're the man!
![image](https://github.com/jfedor2/hid-remapper/assets/8941288/a70f71f2-e750-4882-909b-ca946ac7638f)

**Comment by jfedor2** [comment]
Great! I will include the fix in the next release.

**Comment by jfedor2** [comment]
This is now in the latest release.
