### ISSUE TITLE
Add momentary/tap layer/action  aka QMK LT()

### ISSUE THREAD

**Issue by b-** [jfedor2/hid-remapper#8]
The best way to explain what I'm looking for is to quote QMK documentation for its equivalent LT() feature:

> `LT(layer, kc)` - momentarily activates _layer_ when held, and sends _kc_ when tapped.

So the idea is I would set, e.g., the _back_ button as an input, and the output would be switching to another layer while I hold it down, but if I release it within e.g., 250ms the remapper will issue a _back_ button press.

**Comment by jfedor2** [comment]
Check out the latest release, it adds a "tap-hold" mechanism.

It's not as sophisticated as the one in QMK, but should cover the basic scenarios.
