### ISSUE TITLE
yo thank you for a beatiful tool, any plan to upgrade support of polling rate override to 8k?

### ISSUE THREAD

**Issue by unkn0wnunkn0wn** [jfedor2/hid-remapper#82]
hi 

i am currently using your tool for overclocking mice

just curious if you have plan to add support of 8k polling rate 

thanks

(not issue btw xd)

**Comment by unkn0wnunkn0wn** [comment]
currently remapper is only avaliable with rp2040?

**Comment by jfedor2** [comment]
Yeah.

Well, except for the Bluetooth version which runs on an nRF52840.
