### ISSUE TITLE
Not working with any mouse after the new update.

### ISSUE THREAD

**Issue by chalermla24** [jfedor2/hid-remapper#87]
I am using the dual version. After flashing the new firmware the mouse stopped sending any input to the PC. The mouse does still light up and the board is showing signal when moving/clicking the mouse. No idea what cause this. Rolling back to the previous firmware fixed the problem.

**Comment by jfedor2** [comment]
Did you also flash the B side when upgrading? With this release you have to flash both (always a good idea).

**Comment by chalermla24** [comment]
Yes,  after flashing the A side I flash the B side using the "Flash B Side" button in the website.

**Comment by chalermla24** [comment]
Weird. After flashing using the BOOTSEL method instead of from the website the device now works perfectly. Should this issue be closed?

**Comment by jfedor2** [comment]
"Flash B side" button works only if you're using the custom boards or if you connected the debug pins between the Picos (SWD/SWDCLK).

**Comment by chalermla24** [comment]
Ah yes. That's explained the problem. I wonder why it works fine until the lastest version.

**Comment by jfedor2** [comment]
B side rarely changes so usually you can get away with not updating it.
